import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from 'fs';
import { join } from 'path';

const SKILLS_DIR = process.env.WORKBUDDY_SKILLS_DIR || join(__dirname, '..', '..', 'skills');

interface SkillInfo {
  slug: string;
  name: string;
  description: string;
  description_zh: string;
  version: string;
  category: string;
  quality: string;
  tags: string;
}

function parseSimpleYaml(content: string): Record<string, string> {
  const meta: Record<string, string> = {};
  const keys = ['name', 'description', 'description_zh', 'version', 'description_en', 'homepage'];
  for (const key of keys) {
    const regex = new RegExp(`^${key}:\\s*["']?([^"'\n]+)`, 'm');
    const m = content.match(regex);
    if (m) meta[key] = m[1].trim().replace(/^["']|["']$/g, '');
  }

  const tagsMatch = content.match(/^metadata:\s*\n\s+tags:\s*\[([^\]]+)\]/m);
  if (tagsMatch) meta['tags_raw'] = tagsMatch[1].trim();

  const categoryMatch = content.match(/^metadata:\s*\n(?:\s+.+\n)*\s+category:\s*["']?([^"'\n]+)/m);
  if (categoryMatch) meta['category'] = categoryMatch[1].trim();

  const qualityMatch = content.match(/^metadata:\s*\n(?:\s+.+\n)*\s+quality:\s*["']?([^"'\n]+)/m);
  if (qualityMatch) meta['quality'] = qualityMatch[1].trim();

  return meta;
}

function main() {
  if (!existsSync(SKILLS_DIR)) {
    console.error(`Skills directory not found: ${SKILLS_DIR}`);
    process.exit(1);
  }

  const skillDirs = readdirSync(SKILLS_DIR)
    .filter(name => {
      const fullPath = join(SKILLS_DIR, name);
      return statSync(fullPath).isDirectory() && existsSync(join(fullPath, 'SKILL.md'));
    })
    .sort();

  const skills: SkillInfo[] = [];

  for (const slug of skillDirs) {
    const content = readFileSync(join(SKILLS_DIR, slug, 'SKILL.md'), 'utf-8');
    const meta = parseSimpleYaml(content);

    skills.push({
      slug,
      name: meta['name'] || slug,
      description: meta['description'] || '',
      description_zh: meta['description_zh'] || '',
      version: meta['version'] || 'unknown',
      category: meta['category'] || '',
      quality: meta['quality'] || '',
      tags: meta['tags_raw'] || '',
    });
  }

  const lines = [
    '# Skills Index',
    '',
    `Total: ${skills.length} skills`,
    '',
    '| # | Skill | Name | Description (en) | Description (zh) | Version | Category | Quality | Tags |',
    '|---|-------|------|------------------|-------------------|---------|----------|---------|------|',
  ];

  skills.forEach((skill, i) => {
    const desc = skill.description.length > 80 ? skill.description.substring(0, 77) + '...' : skill.description;
    const descZh = skill.description_zh.length > 50 ? skill.description_zh.substring(0, 47) + '...' : skill.description_zh;
    lines.push(
      `| ${i + 1} | [${skill.slug}](../${skill.slug}/) | ${skill.name} | ${desc} | ${descZh} | ${skill.version} | ${skill.category} | ${skill.quality} | ${skill.tags} |`
    );
  });

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('*Generated by `scripts/generate-skill-index.ts`*');

  const outputPath = join(SKILLS_DIR, 'INDEX.md');
  writeFileSync(outputPath, lines.join('\n'), 'utf-8');
  console.log(`Generated INDEX.md with ${skills.length} skills → ${outputPath}`);
}

main();
